apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      test: test
  replicas: 1
  template:
    metadata:
      labels:
        test: test
    spec:
      containers:
        - image: naison/knative:latest
          imagePullPolicy: IfNotPresent
          name: test
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: dockersock
              subPath: docker.sock
            - mountPath: /etc/kubernetes/pki/etcd
              name: etcd
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/
        - name: etcd
          hostPath:
            path: /etc/kubernetes/pki/etcd
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  selector:
    app: test
  ports:
    - port: 80
  type: NodePort
